# Generated by Django 5.2.7 on 2025-10-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='finance_app.accountgroup')),
                ('dr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_accounts', to='finance_app.accountgroup')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='finance_app.account')),
            ],
            options={
                'db_table': 'sub_account',
            },
        ),
    ]
